/**
 * Constantes tipadas para status de vendas.
 * Segue regra U13: proibir strings literais em comparações de domínio.
 */
export const STATUS_VENDAS = {
  EM_PROCESSAMENTO: 'EM_PROCESSAMENTO',
  APROVADA: 'APROVADA',
  CANCELADA: 'CANCELADA',
  ENTREGUE: 'ENTREGUE',
  EM_TROCA: 'EM_TROCA',
  TROCA_AUTORIZADA: 'TROCA_AUTORIZADA',
  TROCA_REJEITADA: 'TROCA_REJEITADA',
  EM_DEVOLUCAO: 'EM_DEVOLUCAO',
  DEVOLUCAO_AUTORIZADA: 'DEVOLUCAO_AUTORIZADA',
  DEVOLUCAO_REJEITADA: 'DEVOLUCAO_REJEITADA',
  CONCLUIDA: 'CONCLUIDA',
  EM_TRANSITO: 'EM_TRANSITO',
} as const;

export type StatusVenda = typeof STATUS_VENDAS[keyof typeof STATUS_VENDAS];
