-- =============================================================================
-- DML 002 — Seed do usuário administrador inicial
-- Sistema: LES – E-Commerce de Livros
-- Execute após 001_seeds_tipos_referencia.sql.
--
-- ATENÇÃO: Este script foi DESATIVADO.
-- O conceito de "Administrador Mestre" foi removido do sistema.
--
-- O sistema agora usa um modelo multi-tenant onde cada administrador
-- gerencia sua própria loja. Use o script 003_seed_multi_tenant_completo.sql
-- para criar 3 administradores, 3 lojas, 15 produtos e 9 clientes.
--
-- Para criar administradores, execute:
-- 1. 001_seeds_tipos_referencia.sql
-- 2. 003_seed_multi_tenant_completo.sql
-- =============================================================================

-- Este script está desativado. Use 003_seed_multi_tenant_completo.sql
-- RAISE NOTICE 'Script 002_seed_usuario_admin_inicial.sql desativado. Use 003_seed_multi_tenant_completo.sql em vez disso.';
