-- Migration: Seed inicial dos padrões de validação de IA
-- Descrição: Popula a tabela padroes_validacao_ia com os padrões estáticos
--            originalmente hardcoded em servicoValidacaoSegurancaIA.ts.
-- Relacionado à: Entrega 9 - IA de Recomendação com Aprendizado Automático

BEGIN;

INSERT INTO livraria_comercial.padroes_validacao_ia (pai_padrao, pai_tipo, pai_origem)
VALUES
  -- blacklist: comandos de sistema
  ('sistema:', 'blacklist', 'estatico'),
  ('administrador:', 'blacklist', 'estatico'),
  ('admin:', 'blacklist', 'estatico'),
  ('ignore todas as regras', 'blacklist', 'estatico'),
  ('ignore regras', 'blacklist', 'estatico'),
  ('desative segurança', 'blacklist', 'estatico'),
  ('desative filtros', 'blacklist', 'estatico'),
  -- blacklist: produtos falsos
  ('inventados', 'blacklist', 'estatico'),
  ('falsos', 'blacklist', 'estatico'),
  ('não existem', 'blacklist', 'estatico'),
  ('nao existem', 'blacklist', 'estatico'),
  ('produtos que não existem', 'blacklist', 'estatico'),
  ('produtos que nao existem', 'blacklist', 'estatico'),
  ('criar produtos', 'blacklist', 'estatico'),
  ('inventar produtos', 'blacklist', 'estatico'),
  ('gerar produtos', 'blacklist', 'estatico'),
  -- blacklist: manipulação de contexto
  ('como administrador', 'blacklist', 'estatico'),
  ('como admin', 'blacklist', 'estatico'),
  ('como sistema', 'blacklist', 'estatico'),
  ('modo administrador', 'blacklist', 'estatico'),
  ('modo admin', 'blacklist', 'estatico'),
  ('modo sistema', 'blacklist', 'estatico'),
  -- blacklist: bypass
  ('bypass', 'blacklist', 'estatico'),
  ('contornar', 'blacklist', 'estatico'),
  ('evitar filtros', 'blacklist', 'estatico'),
  ('ignorar validação', 'blacklist', 'estatico'),
  ('ignorar validacao', 'blacklist', 'estatico'),

  -- impossivel: listagem completa
  ('mostrar todos os livros do banco', 'impossivel', 'estatico'),
  ('listar todos os produtos', 'impossivel', 'estatico'),
  ('mostrar catálogo completo', 'impossivel', 'estatico'),
  ('mostrar catalogo completo', 'impossivel', 'estatico'),
  ('todos os livros', 'impossivel', 'estatico'),
  ('toda a base', 'impossivel', 'estatico'),
  ('base completa', 'impossivel', 'estatico'),
  -- impossivel: habilidades sobrenaturais
  ('aprender a voar', 'impossivel', 'estatico'),
  ('voar sem avião', 'impossivel', 'estatico'),
  ('voar sem equipamento', 'impossivel', 'estatico'),
  ('respirar embaixo d''água', 'impossivel', 'estatico'),
  ('respirar embaixo dagua', 'impossivel', 'estatico'),
  ('respirar debaixo d''água', 'impossivel', 'estatico'),
  ('respirar debaixo dagua', 'impossivel', 'estatico'),
  ('invisibilidade', 'impossivel', 'estatico'),
  ('ficar invisível', 'impossivel', 'estatico'),
  ('ficar invisivel', 'impossivel', 'estatico'),
  ('telepatia', 'impossivel', 'estatico'),
  ('ler mentes', 'impossivel', 'estatico'),
  ('telecinese', 'impossivel', 'estatico'),
  ('mover objetos com a mente', 'impossivel', 'estatico'),
  ('curar com as mãos', 'impossivel', 'estatico'),
  ('cura milagrosa', 'impossivel', 'estatico'),
  ('imortalidade', 'impossivel', 'estatico'),
  ('viver para sempre', 'impossivel', 'estatico'),
  ('parar o tempo', 'impossivel', 'estatico'),
  ('congelar o tempo', 'impossivel', 'estatico'),
  ('viajar no tempo', 'impossivel', 'estatico'),
  ('voltar no tempo', 'impossivel', 'estatico'),
  ('ir para o futuro', 'impossivel', 'estatico'),
  ('ir para o passado', 'impossivel', 'estatico'),
  -- impossivel: transformações
  ('transformar pedras em ouro', 'impossivel', 'estatico'),
  ('transformar metal em ouro', 'impossivel', 'estatico'),
  ('transformar em ouro', 'impossivel', 'estatico'),
  ('transmutação', 'impossivel', 'estatico'),
  ('transmutacao', 'impossivel', 'estatico'),
  ('transformar gato em', 'impossivel', 'estatico'),
  ('transformar animal em', 'impossivel', 'estatico'),
  ('transformar pessoa em', 'impossivel', 'estatico'),
  ('transformar em dragão', 'impossivel', 'estatico'),
  ('transformar em monstro', 'impossivel', 'estatico'),
  ('criar vida', 'impossivel', 'estatico'),
  ('reviver mortos', 'impossivel', 'estatico'),
  ('trazer de volta à vida', 'impossivel', 'estatico'),
  ('trazer de volta a vida', 'impossivel', 'estatico'),
  ('ressuscitar', 'impossivel', 'estatico'),
  -- impossivel: construções
  ('construir nave espacial com papel', 'impossivel', 'estatico'),
  ('construir nave espacial com cola', 'impossivel', 'estatico'),
  ('construir avião de papel que voe', 'impossivel', 'estatico'),
  ('construir casa de cartas que não caia', 'impossivel', 'estatico'),
  ('construir ponte de palitos', 'impossivel', 'estatico'),
  -- impossivel: sobrenatural
  ('conversar com fantasmas', 'impossivel', 'estatico'),
  ('falar com fantasmas', 'impossivel', 'estatico'),
  ('comunicar com mortos', 'impossivel', 'estatico'),
  ('falar com mortos', 'impossivel', 'estatico'),
  ('invocar espíritos', 'impossivel', 'estatico'),
  ('invocar espiritos', 'impossivel', 'estatico'),
  ('contatar alienígenas', 'impossivel', 'estatico'),
  ('contatar alienigenas', 'impossivel', 'estatico'),
  -- impossivel: magia
  ('lançar feitiços', 'impossivel', 'estatico'),
  ('lançar feiticos', 'impossivel', 'estatico'),
  ('magia negra', 'impossivel', 'estatico'),
  ('magia branca', 'impossivel', 'estatico'),
  ('poderes mágicos', 'impossivel', 'estatico'),
  ('poderes magicos', 'impossivel', 'estatico'),
  ('bruxaria', 'impossivel', 'estatico'),
  ('feitiçaria', 'impossivel', 'estatico'),
  ('feiticaria', 'impossivel', 'estatico'),
  -- impossivel: objetos fictícios
  ('varinha mágica', 'impossivel', 'estatico'),
  ('varinha magica', 'impossivel', 'estatico'),
  ('poção mágica', 'impossivel', 'estatico'),
  ('pocao magica', 'impossivel', 'estatico'),
  ('anel do poder', 'impossivel', 'estatico'),
  ('espada mágica', 'impossivel', 'estatico'),
  ('espada magica', 'impossivel', 'estatico'),
  ('pedra filosofal', 'impossivel', 'estatico'),
  -- impossivel: biológico
  ('mudar de cor', 'impossivel', 'estatico'),
  ('mudar de forma', 'impossivel', 'estatico'),
  ('transformar-se em', 'impossivel', 'estatico'),
  ('crescer asas', 'impossivel', 'estatico'),
  ('ter olhos laser', 'impossivel', 'estatico'),
  ('super força', 'impossivel', 'estatico'),
  ('super forca', 'impossivel', 'estatico'),
  ('velocidade supersônica', 'impossivel', 'estatico'),
  ('velocidade supersonica', 'impossivel', 'estatico'),
  -- impossivel: leitura física impossível
  ('enquanto estou nadando', 'impossivel', 'estatico'),
  ('enquanto estou nado', 'impossivel', 'estatico'),
  ('durante natação', 'impossivel', 'estatico'),
  ('durante natacao', 'impossivel', 'estatico'),
  ('enquanto nado', 'impossivel', 'estatico'),
  ('enquanto estou pulando de paraquedas', 'impossivel', 'estatico'),
  ('enquanto estou pulando paraquedas', 'impossivel', 'estatico'),
  ('durante queda livre', 'impossivel', 'estatico'),
  ('durante salto paraquedas', 'impossivel', 'estatico'),
  ('enquanto estou correndo', 'impossivel', 'estatico'),
  ('durante corrida', 'impossivel', 'estatico'),
  ('enquanto estou dirigindo', 'impossivel', 'estatico'),
  ('durante direção', 'impossivel', 'estatico'),
  ('durante direcao', 'impossivel', 'estatico'),
  ('enquanto estou pilotando', 'impossivel', 'estatico'),
  ('durante voo', 'impossivel', 'estatico'),
  ('enquanto estou voando', 'impossivel', 'estatico'),
  ('durante escalada', 'impossivel', 'estatico'),
  ('enquanto estou escalando', 'impossivel', 'estatico'),
  ('durante surf', 'impossivel', 'estatico'),
  ('enquanto estou surfando', 'impossivel', 'estatico'),
  ('durante mergulho', 'impossivel', 'estatico'),
  ('enquanto estou mergulhando', 'impossivel', 'estatico'),
  ('durante combate', 'impossivel', 'estatico'),
  ('enquanto estou lutando', 'impossivel', 'estatico'),
  ('durante luta', 'impossivel', 'estatico'),
  ('enquanto estou praticando esporte', 'impossivel', 'estatico'),
  ('durante exercício', 'impossivel', 'estatico'),
  ('durante exercicio', 'impossivel', 'estatico'),
  ('enquanto estou treinando', 'impossivel', 'estatico'),
  ('durante treino', 'impossivel', 'estatico'),
  -- impossivel: sono
  ('enquanto durmo', 'impossivel', 'estatico'),
  ('enquanto estou dormindo', 'impossivel', 'estatico'),
  ('durante sono', 'impossivel', 'estatico'),
  ('enquanto estou deitado', 'impossivel', 'estatico'),
  ('durante descanso', 'impossivel', 'estatico'),
  ('enquanto estou descansando', 'impossivel', 'estatico'),
  ('para ler antes de dormir', 'impossivel', 'estatico'),
  ('para ler na cama', 'impossivel', 'estatico'),
  -- impossivel: preparo de alimentos
  ('enquanto estou cozinhando', 'impossivel', 'estatico'),
  ('durante cozimento', 'impossivel', 'estatico'),
  ('enquanto estou preparando', 'impossivel', 'estatico'),
  ('durante preparo', 'impossivel', 'estatico'),
  ('enquanto estou fazendo comida', 'impossivel', 'estatico'),
  ('enquanto estou cozinhando risotos', 'impossivel', 'estatico'),
  ('enquanto estou cozinhando massa', 'impossivel', 'estatico'),
  ('enquanto estou cozinhando jantar', 'impossivel', 'estatico'),
  ('enquanto estou cozinhando almoço', 'impossivel', 'estatico'),
  ('enquanto estou cozinhando almoco', 'impossivel', 'estatico'),
  ('enquanto estou no fogão', 'impossivel', 'estatico'),
  ('durante preparo de refeição', 'impossivel', 'estatico'),
  ('durante preparo de refeicao', 'impossivel', 'estatico'),
  ('enquanto estou cortando', 'impossivel', 'estatico'),
  ('durante corte', 'impossivel', 'estatico'),
  ('enquanto estou mexendo panela', 'impossivel', 'estatico'),
  ('durante fritura', 'impossivel', 'estatico'),
  ('enquanto estou fritando', 'impossivel', 'estatico'),
  ('enquanto estou assando', 'impossivel', 'estatico'),
  ('durante cozimento no forno', 'impossivel', 'estatico'),
  ('enquanto estou usando faca', 'impossivel', 'estatico'),
  ('durante manipulação de alimentos', 'impossivel', 'estatico'),
  ('durante manipulacao de alimentos', 'impossivel', 'estatico'),
  -- impossivel: atividades manuais
  ('enquanto estou costurando', 'impossivel', 'estatico'),
  ('durante costura', 'impossivel', 'estatico'),
  ('enquanto estou bordando', 'impossivel', 'estatico'),
  ('durante bordado', 'impossivel', 'estatico'),
  ('enquanto estou pintando quadro', 'impossivel', 'estatico'),
  ('durante pintura', 'impossivel', 'estatico'),
  ('enquanto estou esculpindo', 'impossivel', 'estatico'),
  ('durante escultura', 'impossivel', 'estatico'),
  ('enquanto estou trabalhando com madeira', 'impossivel', 'estatico'),
  ('durante marcenaria', 'impossivel', 'estatico'),
  ('enquanto estou trabalhando com metal', 'impossivel', 'estatico'),
  ('durante soldagem', 'impossivel', 'estatico'),
  ('enquanto estou soldando', 'impossivel', 'estatico'),
  ('enquanto estou lixando', 'impossivel', 'estatico'),
  ('durante lixamento', 'impossivel', 'estatico'),
  ('enquanto estou serrar', 'impossivel', 'estatico'),
  ('durante serra', 'impossivel', 'estatico'),
  ('enquanto estou martelando', 'impossivel', 'estatico'),
  ('durante martelada', 'impossivel', 'estatico'),
  ('enquanto estou usando ferramenta', 'impossivel', 'estatico'),
  ('durante uso de ferramentas', 'impossivel', 'estatico')
ON CONFLICT (pai_padrao) DO NOTHING;

COMMIT;
