/**
 * Padrões estáticos de validação de segurança da IA.
 *
 * Servem como seed inicial da tabela padroes_validacao_ia e como
 * fallback quando o banco não está disponível.
 */

export const BLACKLIST_PADROES_ESTATICOS: readonly string[] = [
  // Comandos de sistema explícitos
  'sistema:',
  'administrador:',
  'admin:',
  'ignore todas as regras',
  'ignore regras',
  'desative segurança',
  'desative filtros',

  // Solicitações de produtos falsos/inventados
  'inventados',
  'falsos',
  'não existem',
  'nao existem',
  'produtos que não existem',
  'produtos que nao existem',
  'criar produtos',
  'inventar produtos',
  'gerar produtos',

  // Tentativas de manipulação de contexto
  'como administrador',
  'como admin',
  'como sistema',
  'modo administrador',
  'modo admin',
  'modo sistema',

  // Tentativas de bypass de segurança
  'bypass',
  'contornar',
  'evitar filtros',
  'ignorar validação',
  'ignorar validacao',

  // Injeção via histórico / roleplay adversarial
  'ignore filtros',
  'ignorar filtros',
  'modo irrestrito',
  'sem filtros',
  'sem restrições',
  'sem restricoes',
  'sem limitações',
  'sem limitacoes',
  'instrucao interna',
  'instrução interna',
  'system override',
  'system prompt',
  'prompt interno',
  'regras anteriores',
  'instruções anteriores',
  'instrucoes anteriores',
  'modo sem restrições',
  'modo sem restricoes',
  'responda qualquer',
  'responda tudo',
  'pode tudo',
  'sem bloqueios',
  'sem censura',
  'desative todas',
  'desative todos',
  'libere acesso',
  'acesso irrestrito',
  'acesso root',
  'acesso total',
  'dump_all',
  'dump all',
];

export const PADROES_IMPOSSIVEIS_ESTATICOS: readonly string[] = [
  // Solicitações de listagem completa
  'mostrar todos os livros do banco',
  'listar todos os produtos',
  'mostrar catálogo completo',
  'mostrar catalogo completo',
  'todos os livros',
  'toda a base',
  'base completa',

  // Habilidades sobrenaturais
  'aprender a voar',
  'voar sem avião',
  'voar sem equipamento',
  'respirar embaixo d\'água',
  'respirar embaixo dagua',
  'respirar debaixo d\'água',
  'respirar debaixo dagua',
  'invisibilidade',
  'ficar invisível',
  'ficar invisivel',
  'telepatia',
  'ler mentes',
  'telecinese',
  'mover objetos com a mente',
  'curar com as mãos',
  'cura milagrosa',
  'imortalidade',
  'viver para sempre',
  'parar o tempo',
  'congelar o tempo',
  'viajar no tempo',
  'voltar no tempo',
  'ir para o futuro',
  'ir para o passado',

  // Transformações impossíveis
  'transformar pedras em ouro',
  'transformar metal em ouro',
  'transformar em ouro',
  'transmutação',
  'transmutacao',
  'transformar gato em',
  'transformar animal em',
  'transformar pessoa em',
  'transformar em dragão',
  'transformar em monstro',
  'criar vida',
  'reviver mortos',
  'trazer de volta à vida',
  'trazer de volta a vida',
  'ressuscitar',

  // Construções impossíveis
  'construir nave espacial com papel',
  'construir nave espacial com cola',
  'construir avião de papel que voe',
  'construir casa de cartas que não caia',
  'construir ponte de palitos',

  // Comunicação sobrenatural
  'conversar com fantasmas',
  'falar com fantasmas',
  'comunicar com mortos',
  'falar com mortos',
  'invocar espíritos',
  'invocar espiritos',
  'contatar alienígenas',
  'contatar alienigenas',

  // Habilidades mágicas
  'lançar feitiços',
  'lançar feiticos',
  'magia negra',
  'magia branca',
  'poderes mágicos',
  'poderes magicos',
  'bruxaria',
  'feitiçaria',
  'feiticaria',

  // Objetos fictícios
  'varinha mágica',
  'varinha magica',
  'poção mágica',
  'pocao magica',
  'anel do poder',
  'espada mágica',
  'espada magica',
  'pedra filosofal',

  // Ações biologicamente impossíveis
  'mudar de cor',
  'mudar de forma',
  'transformar-se em',
  'crescer asas',
  'ter olhos laser',
  'super força',
  'super forca',
  'velocidade supersônica',
  'velocidade supersonica',

  // Contextos fisicamente impossíveis de leitura
  'enquanto estou nadando',
  'enquanto estou nado',
  'durante natação',
  'durante natacao',
  'enquanto nado',
  'enquanto estou pulando de paraquedas',
  'enquanto estou pulando paraquedas',
  'durante queda livre',
  'durante salto paraquedas',
  'enquanto estou correndo',
  'durante corrida',
  'enquanto estou dirigindo',
  'durante direção',
  'durante direcao',
  'enquanto estou pilotando',
  'durante voo',
  'enquanto estou voando',
  'durante escalada',
  'enquanto estou escalando',
  'durante surf',
  'enquanto estou surfando',
  'durante mergulho',
  'enquanto estou mergulhando',
  'durante combate',
  'enquanto estou lutando',
  'durante luta',
  'enquanto estou praticando esporte',
  'durante exercício',
  'durante exercicio',
  'enquanto estou treinando',
  'durante treino',

  // Contextos de sono
  'enquanto durmo',
  'enquanto estou dormindo',
  'durante sono',
  'enquanto estou deitado',
  'durante descanso',
  'enquanto estou descansando',
  'para ler antes de dormir',
  'para ler na cama',

  // Contextos de preparo de alimentos
  'enquanto estou cozinhando',
  'durante cozimento',
  'enquanto estou preparando',
  'durante preparo',
  'enquanto estou fazendo comida',
  'enquanto estou cozinhando risotos',
  'enquanto estou cozinhando massa',
  'enquanto estou cozinhando jantar',
  'enquanto estou cozinhando almoço',
  'enquanto estou cozinhando almoco',
  'enquanto estou no fogão',
  'durante preparo de refeição',
  'durante preparo de refeicao',
  'enquanto estou cortando',
  'durante corte',
  'enquanto estou mexendo panela',
  'durante fritura',
  'enquanto estou fritando',
  'enquanto estou assando',
  'durante cozimento no forno',
  'enquanto estou usando faca',
  'durante manipulação de alimentos',
  'durante manipulacao de alimentos',

  // Atividades manuais intensas
  'enquanto estou costurando',
  'durante costura',
  'enquanto estou bordando',
  'durante bordado',
  'enquanto estou pintando quadro',
  'durante pintura',
  'enquanto estou esculpindo',
  'durante escultura',
  'enquanto estou trabalhando com madeira',
  'durante marcenaria',
  'enquanto estou trabalhando com metal',
  'durante soldagem',
  'enquanto estou soldando',
  'enquanto estou lixando',
  'durante lixamento',
  'enquanto estou serrar',
  'durante serra',
  'enquanto estou martelando',
  'durante martelada',
  'enquanto estou usando ferramenta',
  'durante uso de ferramentas',
];
